### ISSUE TITLE
TypeError: null is not a string

### ISSUE THREAD

**Issue by repomorphic** [vHanda/google-keep-exporter#1]
Hello everyone. I have two folders in the project folder. One is the source folder which is downloaded from Google Takeout other is Output folder. When I have tried the following:
`node main.js ./Takeout ./Output`

It gives me 

> /home/q/Downloads/google-keep-exporter-master/node_modules/to-markdown/index.js:195
>     throw new TypeError(input + ' is not a string')
>     ^
> 
> TypeError: null is not a string
>     at toMarkdown (/home/q/Downloads/google-keep-exporter-master/node_modules/to-markdown/index.js:195:11)
>     at parse (/home/q/Downloads/google-keep-exporter-master/parser.js:47:17)
>     at convert (/home/q/Downloads/google-keep-exporter-master/main.js:28:13)
>     at files.forEach.filePath (/home/q/Downloads/google-keep-exporter-master/main.js:39:27)
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/home/q/Downloads/google-keep-exporter-master/main.js:39:7)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)

Would you help me to solve this issue?

**Comment by vHanda** [comment]
Hi. You bug report inspired me to update this project.

Could you please try it out now?
```
git clone git@github.com:vHanda/google-keep-exporter.git
cd google-keep-exporter
npm install
npm run build
node dist/main.js <input> <outputDir>
```

The `input` can either be the zip file or the directory where it was unzipped.
