### ISSUE TITLE
 [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by qwertyuser1983** [vHanda/google-keep-exporter#10]
Tried to to convert ~700 notes, ~6.7 GB, end prematurely. 

./google-keep-exporter-linux Keep MarkDown
Converted 236 notes
Output Dir: MarkDown
(node:5734) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by jimcarst** [comment]
This error still occurs on Win10.
