### ISSUE TITLE
NOT WORKING: Outputs 0 files. 

### ISSUE THREAD

**Issue by Harmanjit** [vHanda/google-keep-exporter#23]
The program runs successfully and the output directory has 0 files.

**Comment by vHanda** [comment]
Yeah. The format has changed over time

Going to mark the project as archived.

**Comment by Harmanjit** [comment]
This repo worked for me:https://github.com/erikelisath/keep-to-markdown. 
Maybe provide a link to this for someone who stumbles on this webpage?
Thanks for prompt response!

**Comment by vHanda** [comment]
Makes sense. I'll update the readme with a link to it. Thanks!
