### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by pcuellar** [vHanda/google-keep-exporter#9]
Hello, 

I keep getting an error on the output apparently related to the length of a note at the output, Here is the log:

`UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open 'output/`

My conf is:
MacOS 10.15.5
node v12.18.0
npm 6.14.4

**Comment by pcuellar** [comment]
Noticed pull request hasn't been merged. Will leave opened in the meantime.

**Comment by MuoabdlwhabMhdeiBin** [comment]
UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open 'output/
